In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

In [3]:
red_wine = pd.read_csv(Path('Resources/Red.csv'))
red_wine.head()

Name  Country     Region  \
0                        Pomerol 2011   France    Pomerol   
1                          Lirac 2017   France      Lirac   
2  Erta e China Rosso di Toscana 2015    Italy    Toscana   
3                      Bardolino 2019    Italy  Bardolino   
4      Ried Scheibner Pinot Noir 2016  Austria  Carnuntum   

                  Winery  Rating  NumberOfRatings  Price  Year  
0  Château La Providence     4.2              100  95.00  2011  
1     Château Mont-Redon     4.3              100  15.50  2017  
2             Renzo Masi     3.9              100   7.45  2015  
3             Cavalchina     3.5              100   8.72  2019  
4            Markowitsch     3.9              100  29.15  2016

In [15]:
red_wine.dtypes

Name                object
Country             object
Region              object
Winery              object
Rating             float64
NumberOfRatings      int64
Price              float64
Year                object
dtype: object

In [16]:
for i in range(len(red_wine['Price'])):
    if red_wine['Price'][i] >= 300:
        red_wine.at[i,'Price'] = 2
    elif red_wine['Price'][i] <= 50:
        red_wine.at[i,'Price'] = 0
    else:
        red_wine.at[i,'Price'] = 1


In [18]:
red_wine.head(20)

Name        Country  \
0                                       Pomerol 2011         France   
1                                         Lirac 2017         France   
2                 Erta e China Rosso di Toscana 2015          Italy   
3                                     Bardolino 2019          Italy   
4                     Ried Scheibner Pinot Noir 2016        Austria   
5                   Gigondas (Nobles Terrasses) 2017         France   
6                  Marion's Vineyard Pinot Noir 2016    New Zealand   
7                                     Red Blend 2014          Chile   
8                                       Chianti 2015          Italy   
9                                     Tradition 2014         France   
10                              Chianti Riserva 2013          Italy   
11                                   Descendant 2016      Australia   
12  Les Obriers de la Peira Terrasses du Larzac 2017         France   
13                              Zenas Primitivo 2018          Italy   
14        Cuvée Confidence Côtes du Rhône Rouge 2017         France   
15                                       Shiraz 2018      Australia   
16                           Proprietor's Blend 2016   South Africa   
17                               La Bienquerida 2016          Spain   
18                           Cabernet Sauvignon 2015  United States   
19                    Fulgeo Negroamaro Salento 2016          Italy   

                     Region                    Winery  Rating  \
0                   Pomerol     Château La Providence     4.2   
1                     Lirac        Château Mont-Redon     4.3   
2                   Toscana                Renzo Masi     3.9   
3                 Bardolino                Cavalchina     3.5   
4                 Carnuntum               Markowitsch     3.9   
5                  Gigondas             Vieux Clocher     3.7   
6                 Wairarapa                  Schubert     4.0   
7              Itata Valley             Viña La Causa     3.9   
8                   Chianti         Castello Montaùto     3.6   
9                 Minervois  Domaine des Aires Hautes     3.5   
10                  Chianti               Poggiotondo     3.9   
11                  Barossa                  Torbreck     4.3   
12      Terrasses du Larzac     La Pèira en Damaisèla     4.1   
13                   Puglia                La Bollina     3.6   
14           Côtes-du-Rhône        Domaine Fond Croze     3.7   
15  South Eastern Australia                Barramundi     3.2   
16             Stellenbosch                 Ernie Els     4.2   
17                   Bierzo                    Losada     4.3   
18               California                  Hacienda     3.8   
19                  Salento                San Donaci     4.0   

    NumberOfRatings  Price  Year  
0               100    1.0  2011  
1               100    0.0  2017  
2               100    0.0  2015  
3               100    0.0  2019  
4               100    0.0  2016  
5               100    0.0  2017  
6               100    0.0  2016  
7               100    0.0  2014  
8               100    0.0  2015  
9               100    0.0  2014  
10              100    0.0  2013  
11              100    1.0  2016  
12              100    0.0  2017  
13              100    0.0  2018  
14              100    0.0  2017  
15              100    0.0  2018  
16              100    0.0  2016  
17              100    0.0  2016  
18              100    0.0  2015  
19              100    0.0  2016

In [19]:
red_wine.value_counts("Price")

Price
0.0    7139
1.0    1407
2.0     120
dtype: int64

In [21]:
red_wine = red_wine[red_wine.Year != "N.V."]

In [23]:
red_wine.value_counts("Year")

Year
2016    1776
2017    1558
2015    1396
2018    1099
2014     798
2013     564
2012     371
2011     278
2010     174
2005     154
2019     116
2009      84
2008      80
2006      44
2007      43
2004      27
2000      19
1999      15
2001      12
2003      11
2002       7
1997       7
1998       6
1996       5
1995       4
1992       3
1989       2
1990       2
1993       1
1991       1
1988       1
dtype: int64

In [32]:
y = red_wine["Price"]

X = red_wine.drop(columns=["Price", "Name", "Country", "Region", "Winery"])

In [25]:
y.head()

0    1.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Price, dtype: float64

In [33]:
X.head()

Rating  NumberOfRatings  Year
0     4.2              100  2011
1     4.3              100  2017
2     3.9              100  2015
3     3.5              100  2019
4     3.9              100  2016

In [34]:
y.value_counts()

0.0    7132
1.0    1406
2.0     120
Name: Price, dtype: int64

In [35]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assigned a random_state of 1 to the function

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(6493, 3)

In [37]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
# YOUR CODE HERE!

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
                                random_state=1)
classifier

# Fit the model using training data
classifier.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [38]:
predictions = classifier.predict(X_test)

In [39]:
balanced_accuracy_score(y_test, predictions)

0.4655314714730026

In [40]:
c_matrix = confusion_matrix(y_test, predictions)
print(c_matrix)

[[1705   78    0]
 [ 197  155    0]
 [   1   29    0]]


In [41]:
class_report = classification_report(y_test, predictions)
print(class_report)

              precision    recall  f1-score   support

         0.0       0.90      0.96      0.93      1783
         1.0       0.59      0.44      0.50       352
         2.0       0.00      0.00      0.00        30

    accuracy                           0.86      2165
   macro avg       0.50      0.47      0.48      2165
weighted avg       0.83      0.86      0.84      2165



C:\Users\Luis Santamaria\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Luis Santamaria\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Luis Santamaria\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
