In [1]:
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

In [2]:
white_wine = pd.read_csv(Path('Resources/White.csv'))
white_wine.head()

Name  Country                      Region  \
0          Vermentino 2017    Italy                     Toscana   
1        Ronco Broilo 2010    Italy  Colli Orientali del Friuli   
2  Weisser Schiefer s 2017  Austria               Südburgenland   
3          Chardonnay 2018  Germany                 Rheinhessen   
4     Maganza Zibibbo 2018    Italy             Terre Siciliane   

                    Winery  Rating  NumberOfRatings  Price  Year  
0      Famiglia Castellani     3.8               25   5.65  2017  
1  Conte d'Attimis Maniago     4.3               25  44.90  2010  
2     Weinbau Uwe Schiefer     4.2               25  33.25  2017  
3        Krämer - Straight     3.9               25   8.99  2018  
4                Luna Gaia     3.9               25   8.60  2018

In [3]:
white_wine.dtypes

Name                object
Country             object
Region              object
Winery              object
Rating             float64
NumberOfRatings      int64
Price              float64
Year                object
dtype: object

In [4]:
for i in range(len(white_wine['Price'])):
    if white_wine['Price'][i] >= 300:
        white_wine.at[i,'Price'] = 2
    elif white_wine['Price'][i] <= 50:
        white_wine.at[i,'Price'] = 0
    else:
        white_wine.at[i,'Price'] = 1

In [5]:
white_wine.head(20)

Name  Country  \
0                                     Vermentino 2017    Italy   
1                                   Ronco Broilo 2010    Italy   
2                             Weisser Schiefer s 2017  Austria   
3                                     Chardonnay 2018  Germany   
4                                Maganza Zibibbo 2018    Italy   
5                                     Chardonnay 2019  Germany   
6                           Goldloch Riesling GG 2016  Germany   
7                                  Kieselberg GG 2015  Germany   
8                                     Catarratto 2019    Italy   
9                                Safari Pecorino 2017    Italy   
10                              Sauvignon Veneto 2019    Italy   
11                                 Berg Riesling 2018   France   
12                                     Grechetto 2018    Italy   
13  Riesling 'Le Gallais' Wiltinger Braune Kupp Ka...  Germany   
14                       Unterebner Pinot Grigio 2018    Italy   
15                            The Guv'nor Blanco 2019    Spain   
16       Oestricher Muschelkalk Riesling Trocken 2018  Germany   
17                                  Mâcon-Prissé 2014   France   
18               Kallstadter Steinacker Riesling 2015  Germany   
19                                 Kerner Carned 2018    Italy   

                        Region                           Winery  Rating  \
0                      Toscana              Famiglia Castellani     3.8   
1   Colli Orientali del Friuli          Conte d'Attimis Maniago     4.3   
2                Südburgenland             Weinbau Uwe Schiefer     4.2   
3                  Rheinhessen                Krämer - Straight     3.9   
4              Terre Siciliane                        Luna Gaia     3.9   
5                        Pfalz                        Schneider     3.7   
6                         Nahe                             Diel     4.1   
7                        Pfalz                      Von Winning     4.1   
8              Terre Siciliane  Feudi Branciforti dei Bordonaro     3.8   
9              Terre di Chieti                             Bove     3.4   
10                      Veneto                       Torresella     3.8   
11                      Alsace                  Domaine Pfister     4.2   
12                      Umbria                            SIGNÆ     3.6   
13                   Wiltingen          Egon Müller - Scharzhof     4.3   
14       Südtirol - Alto Adige                           Tramin     3.7   
15                    Castilla                      Félix Solís     3.7   
16                    Rheingau                        Spreitzer     3.8   
17                Mâcon-Prissé     Les Héritiers du Comte Lafon     3.7   
18                       Pfalz                            Rings     4.0   
19       Südtirol - Alto Adige                  Cantina Kaltern     3.7   

    NumberOfRatings  Price  Year  
0                25    0.0  2017  
1                25    0.0  2010  
2                25    0.0  2017  
3                25    0.0  2018  
4                25    0.0  2018  
5                25    0.0  2019  
6                25    0.0  2016  
7                25    0.0  2015  
8                25    0.0  2019  
9                25    0.0  2017  
10               25    0.0  2019  
11               25    0.0  2018  
12               25    0.0  2018  
13               25    0.0  2018  
14               25    0.0  2018  
15               25    0.0  2019  
16               25    0.0  2018  
17               25    0.0  2014  
18               25    0.0  2015  
19               25    0.0  2018

In [6]:
white_wine.value_counts("Price")

Price
0.0    3560
1.0     197
2.0       7
dtype: int64

In [7]:
white_wine = white_wine[white_wine.Year != "N.V."]

In [8]:
white_wine.value_counts("Year")

Year
2018    1440
2017     787
2019     588
2016     484
2015     250
2014      85
2013      42
2012      26
2011      24
2010       5
2006       5
2005       4
2003       3
2007       3
2008       3
2020       2
2009       2
2004       2
1999       2
1998       1
1993       1
dtype: int64

In [10]:
y = white_wine["Price"]

X = white_wine.drop(columns=["Price", "Name", "Country", "Region", "Winery"])

In [12]:
y.head(20)

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
Name: Price, dtype: float64

In [13]:
X.head()

Rating  NumberOfRatings  Year
0     3.8               25  2017
1     4.3               25  2010
2     4.2               25  2017
3     3.9               25  2018
4     3.9               25  2018

In [14]:
y.value_counts()

0.0    3555
1.0     197
2.0       7
Name: Price, dtype: int64

In [15]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assigned a random_state of 1 to the function

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(2819, 3)

In [16]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
# YOUR CODE HERE!

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
                                random_state=1)
classifier

# Fit the model using training data
classifier.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [17]:
predictions = classifier.predict(X_test)

In [35]:
print(f" Training Data Score: {ROS_model.score(X_train, y_train)}")
print(f" Testing Data Score: {ROS_model.score(X_test, y_test)}")
print(f" Balanced Accuracy Score: {balanced_accuracy_score(y_test, y_prediction)}")

 Training Data Score: 0.8424973394820858
 Testing Data Score: 0.8404255319148937
 Balanced Accuracy Score: 0.6810487974717446


In [19]:
c_matrix = confusion_matrix(y_test, predictions)
print(c_matrix)

[[887   2   0]
 [ 38  11   0]
 [  1   1   0]]


In [20]:
class_report = classification_report(y_test, predictions)
print(class_report)

              precision    recall  f1-score   support

         0.0       0.96      1.00      0.98       889
         1.0       0.79      0.22      0.35        49
         2.0       0.00      0.00      0.00         2

    accuracy                           0.96       940
   macro avg       0.58      0.41      0.44       940
weighted avg       0.95      0.96      0.94       940



/Users/kianatalavera/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/kianatalavera/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/kianatalavera/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  

In [22]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
random_over_sampler=RandomOverSampler(random_state = 1)

# Fit the original training data to the random_oversampler model
x_resampled, y_resampled = random_over_sampler.fit_resample(X_train, y_train)

In [23]:
y_resampled.value_counts()

0.0    2666
1.0    2666
2.0    2666
Name: Price, dtype: int64

In [25]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
ros_model = LogisticRegression(solver='lbfgs', random_state=1)


# Fit the model using the resampled training data
ros_model.fit(x_resampled, y_resampled)

# Make a prediction using the testing data
y_prediction = ros_model.predict(X_test)

In [26]:
print(f" Balanced Accuracy Score: {balanced_accuracy_score(y_test, y_prediction)}")

 Balanced Accuracy Score: 0.6810487974717446


In [27]:
ros_test_matrix = confusion_matrix(y_test, y_prediction)
print(ros_test_matrix)

[[755 128   6]
 [  9  34   6]
 [  0   1   1]]


In [28]:
ros_test_report = classification_report(y_test, y_prediction)
print(ros_test_report)

              precision    recall  f1-score   support

         0.0       0.99      0.85      0.91       889
         1.0       0.21      0.69      0.32        49
         2.0       0.08      0.50      0.13         2

    accuracy                           0.84       940
   macro avg       0.42      0.68      0.46       940
weighted avg       0.95      0.84      0.88       940

